// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/platos-core/SignalCommandCenter.tsx": () => import("../components/mockups/platos-core/SignalCommandCenter.tsx"),
  "./components/mockups/platos-core/VariantAccessibility.tsx": () => import("../components/mockups/platos-core/VariantAccessibility.tsx"),
  "./components/mockups/platos-core/VariantHierarchy.tsx": () => import("../components/mockups/platos-core/VariantHierarchy.tsx"),
  "./components/mockups/platos-core/VariantInteraction.tsx": () => import("../components/mockups/platos-core/VariantInteraction.tsx")
};
